<?php
declare(strict_types=1);
final class AdminUserController
{
    private PDO $db;public function __construct(){$this->db=Database::connection();}
    public function index():void{$rows=$this->db->query('SELECT id,name,email,is_active,created_at FROM admins ORDER BY name,id')->fetchAll();Response::json(['data'=>array_map(static fn($r)=>['id'=>(int)$r['id'],'name'=>$r['name'],'email'=>$r['email'],'is_active'=>(bool)$r['is_active'],'created_at'=>$r['created_at']],$rows),'current_admin_id'=>Auth::id()]);}
    public function save():void{$in=json_decode((string)file_get_contents('php://input'),true);$id=(int)($in['id']??0);$name=trim((string)($in['name']??''));$email=strtolower(trim((string)($in['email']??'')));$password=(string)($in['password']??'');$active=!empty($in['is_active'])?1:0;if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||(!$id&&strlen($password)<8)||($password!==''&&strlen($password)<8)){Response::json(['error'=>'Enter a name, valid email and a password of at least 8 characters.'],422);return;}if($id===Auth::id()&&!$active){Response::json(['error'=>'You cannot deactivate your own account.'],422);return;}try{if($id){$sql='UPDATE admins SET name=:name,email=:email,is_active=:active'.($password!==''?',password_hash=:hash':'').' WHERE id=:id';$p=[':name'=>$name,':email'=>$email,':active'=>$active,':id'=>$id];if($password!=='')$p[':hash']=password_hash($password,PASSWORD_DEFAULT);}else{$sql='INSERT INTO admins(name,email,password_hash,is_active) VALUES(:name,:email,:hash,:active)';$p=[':name'=>$name,':email'=>$email,':hash'=>password_hash($password,PASSWORD_DEFAULT),':active'=>$active];}$s=$this->db->prepare($sql);$s->execute($p);Response::json(['data'=>['ok'=>true]]);}catch(PDOException $e){Response::json(['error'=>'That administrator email is already in use.'],409);}}
    public function destroy(int $id):void{if($id===Auth::id()){Response::json(['error'=>'You cannot delete your own account.'],422);return;}$s=$this->db->prepare('DELETE FROM admins WHERE id=:id');$s->execute([':id'=>$id]);Response::json(['data'=>['ok'=>true]]);}
}
