<?php
declare(strict_types=1);
final class PromoCodeController
{
    private PDO $db;
    public function __construct(){ $this->db=Database::connection(); }
    public function validate(): void {$in=json_decode((string)file_get_contents('php://input'),true);$code=strtoupper(trim((string)($in['code']??'')));$subtotal=max(0,(int)($in['subtotal_pesewas']??0));$p=$this->findValid($code,$subtotal);if(!$p){Response::json(['error'=>'This promotional code is invalid, expired, or unavailable.'],422);return;}Response::json(['data'=>['code'=>$p['code'],'discount_pesewas'=>$this->discount($p,$subtotal)]]);}
    public function adminIndex(): void {Response::json(['data'=>$this->db->query('SELECT * FROM promo_codes ORDER BY id DESC')->fetchAll()]);}
    public function save(): void {$in=json_decode((string)file_get_contents('php://input'),true);$code=strtoupper(trim((string)($in['code']??'')));$type=(string)($in['discount_type']??'percent');$value=(int)($in['discount_value']??0);if(!preg_match('/^[A-Z0-9_-]{3,30}$/',$code)||!in_array($type,['percent','fixed'],true)||$value<=0||($type==='percent'&&$value>100)){Response::json(['error'=>'Enter a valid code and discount value.'],422);return;}$p=[':code'=>$code,':type'=>$type,':value'=>$value,':minimum'=>max(0,(int)($in['minimum_pesewas']??0)),':limit'=>max(0,(int)($in['usage_limit']??0)),':starts'=>trim((string)($in['starts_at']??'')),':ends'=>trim((string)($in['ends_at']??'')),':active'=>!empty($in['is_active'])?1:0];$id=(int)($in['id']??0);try{if($id){$p[':id']=$id;$s=$this->db->prepare('UPDATE promo_codes SET code=:code,discount_type=:type,discount_value=:value,minimum_pesewas=:minimum,usage_limit=:limit,starts_at=:starts,ends_at=:ends,is_active=:active WHERE id=:id');}else{$s=$this->db->prepare('INSERT INTO promo_codes(code,discount_type,discount_value,minimum_pesewas,usage_limit,starts_at,ends_at,is_active) VALUES(:code,:type,:value,:minimum,:limit,:starts,:ends,:active)');}$s->execute($p);Response::json(['data'=>['ok'=>true]]);}catch(PDOException $e){Response::json(['error'=>'That promotional code already exists.'],409);}}
    public function destroy(int $id): void {$s=$this->db->prepare('DELETE FROM promo_codes WHERE id=:id');$s->execute([':id'=>$id]);Response::json(['data'=>['ok'=>true]]);}
    public function findValid(string $code,int $subtotal): ?array {if($code==='')return null;$s=$this->db->prepare("SELECT * FROM promo_codes WHERE code=:code AND is_active=1 AND minimum_pesewas<=:subtotal AND (usage_limit=0 OR used_count<usage_limit) AND (starts_at='' OR starts_at<=datetime('now')) AND (ends_at='' OR ends_at>=datetime('now'))");$s->execute([':code'=>$code,':subtotal'=>$subtotal]);return $s->fetch()?:null;}
    public function discount(array $p,int $subtotal): int {return min($subtotal,$p['discount_type']==='percent'?(int)floor($subtotal*(int)$p['discount_value']/100):(int)$p['discount_value']);}
}
